# Generated by Django 3.0.6 on 2020-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('martial_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=20)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('salary', models.BigIntegerField()),
                ('age', models.SmallIntegerField()),
                ('interests', models.TextField()),
                ('date_of_joining', models.DateField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
