# Generated by Django 3.0.6 on 2020-05-24 17:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('es_core', '0002_auto_20200524_1711'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('es_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='MaritalStatus',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20),
        ),
    ]
